### ISSUE TITLE
Cloning Repository

### ISSUE THREAD

**Issue by HarveyCastro2003** [HarveyCastro2003/GROUP-8_IPT2_CASE_STUDY#4]
I cloned our repository from github to a specific folder in my pc

![Issue3](https://github.com/HarveyCastro2003/GROUP-8_IPT2_CASE_STUDY/assets/159202442/1be4211c-ea4a-4268-adad-73da79f14d93)

**Comment by TherenceJSuba** [comment]
Cloned Remote Repository

![image](https://github.com/HarveyCastro2003/GROUP-8_IPT2_CASE_STUDY/assets/159201954/77414707-93d9-4895-95ac-0d4f393ff403)

**Comment by HarveyCastro2003** [comment]
Cloning remote repository is done
