### ISSUE TITLE
HTML Output

### ISSUE THREAD

**Issue by HarveyCastro2003** [HarveyCastro2003/GROUP-8_IPT2_CASE_STUDY#5]
This is the output of my html file for my portfolio

![Issue4](https://github.com/HarveyCastro2003/GROUP-8_IPT2_CASE_STUDY/assets/159202442/7c52e107-329a-4788-9763-364e4101614d)

**Comment by TherenceJSuba** [comment]
This is my HTML Output

![image](https://github.com/HarveyCastro2003/GROUP-8_IPT2_CASE_STUDY/assets/159201954/e434c78f-694e-4048-83fc-6eb71cbc3cd6)

**Comment by HarveyCastro2003** [comment]
All HTML is done
